### ISSUE TITLE
블루 프린터 와 라우팅 코드의 분리

### ISSUE THREAD

**Issue by loganstone** [capkum/luida-server#3]
* 현재 각 app(?) 단위의 \_\_init\_\_.py 에 블루 프린터와 라우팅 코드가 같이 있음
* 블루 프린터가 들어 있는 \_\_init\_\_.py 파일에는 모듈 제어 코드들이 들어가게 될 것임으로
   이를 분리 하는게 좋다고 생각합니다.
* app(?) 단위의 디렉토리 안에 views.py 를 만들어서 라우팅(과 비지니스 로직 코드)는 분리 했으면 합니다.

**Comment by capkum** [comment]
코드 분리 완료
